import { ICoffeeCardProps } from '../CoffeeCard'

import imgExpressoTradicional from '../../../../assets/Type=Expresso.png'

export const defaultCoffeeList: ICoffeeCardProps[] = [
  {
    id: 'expressoTradicional',
    imgSrc: imgExpressoTradicional,
    tags: ['tradicional'],
    title: 'Expresso Tradicional',
    subtitle: 'O tradicional café feito com água quente e grãos moídos',
    price: '9,90',
  },
  {
    id: 'expressoAmericano',
    imgSrc: '/src/assets/Type=Americano.png',
    tags: ['tradicional'],
    title: 'Expresso Americano',
    subtitle: 'Expresso diluído, menos intenso que o tradicional',
    price: '9,90',
  },
  {
    id: 'expressoCremoso',
    imgSrc: '/src/assets/Type=Expresso Cremoso.png',
    tags: ['tradicional'],
    title: 'Expresso Cremoso',
    subtitle: 'Café expresso tradicional com espuma cremosa',
    price: '9,90',
  },
  {
    id: 'expressoGelado',
    imgSrc: '/src/assets/Type=Café Gelado.png',
    tags: ['tradicional', 'gelado'],
    title: 'Expresso Gelado',
    subtitle: 'Bebida preparada com café expresso e cubos de gelo',
    price: '9,90',
  },
  {
    id: 'cafeComLeite',
    imgSrc: '/src/assets/Type=Café com Leite.png',
    tags: ['tradicional', 'com leite'],
    title: 'Café com Leite',
    subtitle: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: '9,90',
  },
  {
    id: 'latte',
    imgSrc: '/src/assets/Type=Latte.png',
    tags: ['tradicional', 'com leite'],
    title: 'Latte',
    subtitle: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: '9,90',
  },
  {
    id: 'capuccino',
    imgSrc: '/src/assets/Type=Capuccino.png',
    tags: ['tradicional', 'com leite'],
    title: 'Capuccino',
    subtitle: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: '9,90',
  },
  {
    id: 'macchiato',
    imgSrc: '/src/assets/Type=Macchiato.png',
    tags: ['tradicional', 'com leite'],
    title: 'Macchiato',
    subtitle: 'Café expresso misturado com um pouco de leite quente e espuma',
    price: '9,90',
  },
  {
    id: 'mocaccino',
    imgSrc: '/src/assets/Type=Mochaccino.png',
    tags: ['tradicional', 'com leite'],
    title: 'Mocaccino',
    subtitle: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: '9,90',
  },
  {
    id: 'chocolateQuente',
    imgSrc: '/src/assets/Type=Chocolate Quente.png',
    tags: ['especial', 'com leite'],
    title: 'Chocolate Quente',
    subtitle: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: '9,90',
  },
  {
    id: 'cubano',
    imgSrc: '/src/assets/Type=Cubano.png',
    tags: ['especial', 'alcoólico', 'gelado'],
    title: 'Cubano',
    subtitle: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: '9,90',
  },
  {
    id: 'havaiano',
    imgSrc: '/src/assets/Type=Havaiano.png',
    tags: ['especial'],
    title: 'Havaiano',
    subtitle: 'Bebida adocicada preparada com café e leite de coco',
    price: '9,90',
  },
  {
    id: 'árabe',
    imgSrc: '/src/assets/Type=Árabe.png',
    tags: ['especial'],
    title: 'Árabe',
    subtitle: 'Bebida preparada com grãos de café árabe e especiarias',
    price: '9,90',
  },
  {
    id: 'irlandês',
    imgSrc: '/src/assets/Type=Irlandês.png',
    tags: ['especial', 'alcoólico'],
    title: 'Irlandês',
    subtitle: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: '9,90',
  },
]
